import Head from "next/head";
import About from "../sections/About";
import Appoinments from "../sections/Appoinments";
import Categories from "../sections/Categories";
import Clients from "../sections/Clients";
import Doctors from "../sections/Doctors";
import Faqs from "../sections/Faqs";
import Hero from "../sections/Hero";

export default function Home() {
  return (
    <div className={``}>
      <Head>
        <title>Minute Medico</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Clients />
      <Categories />
      <About />
      <Doctors />
      <Appoinments />
      <Faqs />
    </div>
  );
}
