import React from "react";
import Head from "next/head";
import FullLayout from "../../sections/dashboard/FullLayout";

const Dashboard = () => {
  return (
    <FullLayout>
      <div className="py-24">
        <Head>
          <title>Minute Medico</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h2>Index</h2>
      </div>
    </FullLayout>
  );
};

export default Dashboard;
